- .travis.yml
Initialized TravisCI, the build fails at the moment as it has no tests. #4 is still pending on tests.
Closes #2
> TravisCI yml file added

- tiptapy/__init__.py
Added support for the Title tag. Closes #8
> TitleTag: Added new node that can convert json to title html tag

- tests/test_tranform.py
* Updated `scan_json_datadir` and `scan_html_datadir` to fix the `directory not found` error.
* Refactored unit tests to a single parameterized test -> `test_html_tag` 
Closes #10
> test_tiptapy.py:Updated scan function and refactored unit tests

- README.md
Add TravisCI badge and format documentation.
> README.md: Add TravisCI badge

- tiptapy/__init__.py
* Added check in the `class BaseContainer(BaseNode):` to handle base missing content node. 
* Explicitly checking the input to `to_html()`
Closes #14
> __init__.py: Add check to handle missing content node in the input

- tests/data/html/ordered_list.html
- tests/data/json/ordered_list.json
- tests/test_tranform.py
- tiptapy/__init__.py
* Added OrderedList tag 
* Fixed Liniting errors
Closes #16
> __init__.py: Add OrderedList tag

- tiptapy/__init__.py
> __init__.py: Add Type Annotations

- tests/data/html/featureimage.html
- tests/data/json/featureimage.json
- tests/test_tranform.py
- tiptapy/__init__.py
- tiptapy/extras.py
* Add Feature Image tag
Closes #20
> tiptapy: add Feature Image tag

- tests/data/html/featuredimage.html
- tests/data/html/featureimage.html
- tests/data/html/image.html
- tests/data/json/featuredimage.json
- tests/data/json/image.json
- tests/test_tranform.py
- tiptapy/extras.py
-  Renamed FeatureImage class to FeaturedImage
- Added tests for Image Block 
-  Updated file structure
```
renamed: tests/data/html/featureimage.html -> tests/data/html/featuredimage.html
renamed: tests/data/json/featureimage.json -> tests/data/json/featuredimage.json
```
> tiptapy/extras.py: Rename FeatureImage -> FeaturedImage

- tests/data/html/embed.html
- tests/data/json/embed.json
- tests/test_tranform.py
- tiptapy/__init__.py
* Added `class Embed(BaseContainer)` that takes in the `type="embed"` and return the HTML.
> Add embed tag

- setup.py
- tests/data/html/featuredimage-missing_caption.html
- tests/data/html/featuredimage-no_caption.html
- tests/data/html/featuredimage.html
- tests/data/html/is_renderable.html
- tests/data/json/is_renderable.json
- tests/test_tranform.py
- tiptapy/__init__.py
- tiptapy/extras.py
* Adds `is_renderable()` method to check a given JSON is valid or not.
* Removed `<picture>` tag from featuredimage
Closes #40
> Adds method to validate JSON before rendering

- CHANGELOG.rst
- tests/data/html/heading.html
- tests/data/json/heading.json
- tests/test_tranform.py
- tiptapy/__init__.py
- Long pending HTML escaping added
- Heading is a container now (missed earlier)
> Heading type correction and escaping

- CHANGELOG.rst
- tests/data/html/mark_tags.html
- tests/data/json/mark_tags.json
- tiptapy/__init__.py
* Anchor tag to add target="_blank" and rel="noopener nofollow" if the link is notfrom know provider.
* Adds config class to store constants
* Adds `is_trusted_link` to check if the domain matches the config's domain.
> Standardized Anchor Tag

- tests/data/html/audio-no_caption.html
- tests/data/html/audio.html
- tests/data/json/audio-no_caption.json
- tests/data/json/audio.json
- tests/test_tranform.py
- tiptapy/extras.py
- tiptapy/templates/stack-audio-player.html
* Added `StackAudio(BaseNode)` to handel `type=audio`
* Added `templates` to store `stack-audio-playes.html`
* Added tests for StackAudio
> Adds Audio Block

- setup.py
- tests/data/html/audio-no_caption.html
- tests/data/html/audio.html
- tiptapy/extras.py
- tiptapy/templates/stack-audio-player.html
* Renamed class `audio-player-disabled` -> `audio-player-initialising`
* Renamed class `class="player-button gold-button` ->
`class="player-button`
* Added `style="width: 0;"` to `class="progress-bar"`
* Added `class="audio-player-container"` to figure block
> Updates Audio Player Template

- tests/data/html/code_block.html
- tests/data/json/code_block.json
- tests/test_tranform.py
- tiptapy/__init__.py
> Adds Code block

- tests/test_helper.py
Tests for Text Node's helper function `is_trusted_link()`
that checks config's Domain and adds target & rel.
> tests/test_helper:Added tests for 'is_trusted_link()'

- tests/data/html/paragraph-codemark.html
- tests/data/json/paragraph-codemark.json
- tests/test_tranform.py
- tiptapy/__init__.py
* Updated `mark_tags` to support `code` mark
* Added test for `code` mark
> Adds `code` mark in Class Text

- tests/data/html/document-pdf.html
- tests/data/json/document-pdf.json
- tests/test_tranform.py
- tiptapy/extras.py
- tiptapy/templates/stack-document.html
* Added StackDocument Class in extras.py
* Added document template
* Added tests for document node
> Adds StackDocument to render document node

- CHANGELOG.rst
- setup.cfg
- setup.py
- tests/data/html/document-sketch.html
- tests/data/json/document-sketch.json
- tests/test_tranform.py
- tiptapy/__init__.py
- tiptapy/extras.py
- tiptapy/templates/stack-document.html
This is as per request from the frontend team
> replace fileicon with filetype class

- CHANGELOG.rst
- setup.py
- tiptapy/__init__.py
* Bumps version from 0.11.1 -> 0.12.0
> Bump Version 0.11.1 -> 0.12.0
